CREATE TABLE MATERIAS(
	ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	CODIGO VARCHAR(20),
	CODIGO_ABR VARCHAR(20),
	DESCRIPCION VARCHAR(250),
	FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT current_timestamp
);

INSERT INTO MATERIAS (CODIGO,CODIGO_ABR, DESCRIPCION) VALUES
	('AVM941 ','AVM941','Álgebra Vectorial y Matrices'),
	('DPS941','DPS941','Diseño y Programación de Software Multiplataforma'),
	('GEA941','GEA941','Gestión Ambiental'),
	('PSC901','PSC901','Pensamiento Social Cristiano');

CREATE TABLE CICLOS(
	ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	CODIGO VARCHAR(20),
	ANNIO INT,
	FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT current_timestamp
);


INSERT INTO CICLOS (CODIGO, ANNIO) VALUES
	('01', 2024);

CREATE TABLE PROFESORES(
	ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	CARNET VARCHAR(20) UNIQUE NOT NULL,
	NOMBRES VARCHAR(100),
	APELLIDOS VARCHAR(100),
	CORREO VARCHAR(100) UNIQUE NOT NULL,
	FECHA_CREACION TIMESTAMP NOT NULL DEFAULT current_timestamp,
	ACTIVO BOOLEAN DEFAULT '0' NOT NULL
);

INSERT INTO PROFESORES (CARNET, NOMBRES, APELLIDOS, CORREO, ACTIVO) VALUES
	('MZ142582', 'JOSUE ERASMO', 'MENENDEZ ZEPEDA', 'josue.menendez23@gmail.com',true);


CREATE TABLE ALUMNOS(
	ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	CARNET VARCHAR(20) UNIQUE NOT NULL,
	NOMBRES VARCHAR(100),
	APELLIDOS VARCHAR(100),
	CORREO VARCHAR(100) UNIQUE NOT NULL,
	FECHA_CREACION TIMESTAMP NOT NULL DEFAULT current_timestamp
);

INSERT INTO ALUMNOS (CARNET, NOMBRES, APELLIDOS, CORREO) VALUES 
	('VV121782 ', 'Luis Eduardo', 'Vásquez Villalta', 'vasquez.eduardoluis@gmail.com'),
	('EQ202542', 'Jose Pablo', 'Escobar Quintanilla', 'jose.quintanilla@gmail.com');

CREATE TABLE CICLO_MATERIA (
	ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	ID_CICLO INT NOT NULL,
	ID_MATERIA INT NOT NULL,
	ID_PROFESOR INT NOT NULL,
	FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT current_timestamp,
	CONSTRAINT FK_CICLO_MATERIA_CICLO
	FOREIGN KEY (ID_CICLO) REFERENCES CICLOS(ID),
	CONSTRAINT FK_CICLO_MATERIA_MATERIA
	FOREIGN KEY (ID_MATERIA) REFERENCES MATERIAS(ID),
	CONSTRAINT FK_CICLO_MATERIA_PROFESORES
	FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESORES(ID)
);

CREATE TABLE MATERIA_EVALUACION (
	ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	ID_CICLO_MATERIA INT NOT NULL,
	PORCENTAJE DECIMAL NOT NULL,
	DESCRIPCION VARCHAR(200),
	FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT current_timestamp,
	CONSTRAINT FK_MATERIA_EVALUACION_CICLO_MATERIA
	FOREIGN KEY (ID_CICLO_MATERIA) REFERENCES CICLO_MATERIA(ID)
);


CREATE TABLE NOTAS (
	ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	ID_ESTUDIANTE INT NOT NULL,
	ID_MATERIA_EVALUACION INT NOT NULL,
	NOTA DECIMAL NOT NULL,
	FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT current_timestamp,
	CONSTRAINT FK_NOTAS_ALUMNOS
	FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ALUMNOS(ID),
	CONSTRAINT FK_NOTAS_MATERIA_EVALUACION
	FOREIGN KEY (ID_MATERIA_EVALUACION) REFERENCES MATERIA_EVALUACION(ID)
);

INSERT INTO CICLO_MATERIA(ID_CICLO, ID_MATERIA, ID_PROFESOR) VALUES
	((SELECT ID FROM  CICLOS WHERE CODIGO= '01' AND ANNIO = 2024),
		(SELECT ID FROM  MATERIAS WHERE CODIGO= 'DPS941'),
		(SELECT ID FROM PROFESORES WHERE CARNET='MZ142582')),
	((SELECT ID FROM  CICLOS WHERE CODIGO= '01' AND ANNIO = 2024),
		(SELECT ID FROM  MATERIAS WHERE CODIGO= 'AVM941 '),
		(SELECT ID FROM PROFESORES WHERE CARNET='MZ142582')),
	((SELECT ID FROM  CICLOS WHERE CODIGO= '01' AND ANNIO = 2024),
		(SELECT ID FROM  MATERIAS WHERE CODIGO= 'GEA941'),
		(SELECT ID FROM PROFESORES WHERE CARNET='MZ142582')),
	((SELECT ID FROM  CICLOS WHERE CODIGO= '01' AND ANNIO = 2024),
		(SELECT ID FROM  MATERIAS WHERE CODIGO= 'PSC901'),
		(SELECT ID FROM PROFESORES WHERE CARNET='MZ142582'));


INSERT INTO MATERIA_EVALUACION (ID_CICLO_MATERIA, PORCENTAJE, DESCRIPCION) VALUES 
	(1,15,'TAREA DE INVESTIGACION'),
	(1,15,'Foro de Discusión'),
	(1,20, 'PROYECTO FASE 1'),
	(1,20, 'PROYECTO FASE 2'),
	(1,30, 'PROYECTO FASE 3'),
	(2,10, 'Guia de Ejercicio 1'),
	(2,15, 'Guia de Ejercicio 2'),
	(2,25, 'Examen Parcial 1'),
	(2,25, 'Examen Parcial 2'),
	(2,25, 'Examen Parcial 3');

INSERT INTO NOTAS (ID_ESTUDIANTE , ID_MATERIA_EVALUACION,NOTA) VALUES
	((SELECT ID FROM ALUMNOS WHERE CODIGO = 'VV121782'),1, 8.6),
	((SELECT ID FROM ALUMNOS WHERE CODIGO = 'VV121782'),2, 9),
	((SELECT ID FROM ALUMNOS WHERE CODIGO = 'VV121782'),3, 10),
	((SELECT ID FROM ALUMNOS WHERE CODIGO = 'EQ202542'),1, 7),
	((SELECT ID FROM ALUMNOS WHERE CODIGO = 'EQ202542'),2, 4),
	((SELECT ID FROM ALUMNOS WHERE CODIGO = 'EQ202542'),3, 8),
	((SELECT ID FROM ALUMNOS WHERE CODIGO = 'VV121782'),6, 9.5),
	((SELECT ID FROM ALUMNOS WHERE CODIGO = 'VV121782'),8, 5);